config/routes.rb
Wbangular::Application.routes.draw do
  resources :expenses

  get "welcome/index"

  root 'welcome#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery

  after_filter :set_csrf_cookie_for_ng
  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected
    def verified_request?
      super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
respond_to :json
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :category, :amount, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name %></td>
        <td><%= expense.category %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.date %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="WbangularClient" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wbangular" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <meta id='csrf' ng-controller="CsrfCtrl".
      data-csrf="<%= form_authenticity_token%>">

    <!-- <link href="assets/favicon.ico" rel="shortcut icon"> -->
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Wbangular</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <!-- main menu models -->
<li><%= link_to 'Expenses', expenses_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <!-- templates load here -->
          <div ng-view class="span9"></div>
          <!-- templates load here -->
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <!-- sidebar menu models -->
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>